REM   Script: Session 02
REM   FST M4 assignemnt

create table STUDENT 
( 
    StudentName VARCHAR2(50) NOT NULL, 
    StudentRollNo VARCHAR2(10) CONSTRAINT RollNo_PKey PRIMARY KEY, 
    StudentClass VARCHAR2(5) NOT NULL, 
    StudentAge NUMBER(5) NOT NULL, 
    StudentFatherName VARCHAR2(50) 
);

DESC STUDENT


SELECT * FROM STUDENT;

INSERT INTO STUDENT VALUES('AJAY KUMAR','IETLINF01','X',16,'PREM KUMAR');

INSERT INTO STUDENT VALUES('RAJAT MISHRA','IETLINF02','XI',17,'PANKAJ MISHRA');

INSERT INTO STUDENT VALUES('SUDHEER SHARMA','IETLINF03','IX',15,'SUNDER SHARMA');

INSERT INTO STUDENT VALUES('NANCY KAUR','IETLINF04','XII',18,'AK SINGH');

INSERT INTO STUDENT VALUES('SUMITA SHARMA','IETLINF05','IV',14,'AJAY SHARMA');

INSERT INTO STUDENT VALUES('NANDINI GUPTA','IETLINF06','VII',18,'RAM GUPTA');

INSERT INTO STUDENT VALUES('RAM KUMAR','IETLINF07','X',16,'RAMAN KUMAR');

SELECT * FROM STUDENT;

SELECT StudentClass, COUNT(StudentRollNo) AS Total_Count FROM STUDENT GROUP BY StudentClass;

SELECT COUNT(StudentRollNo) AS Total_Count FROM STUDENT GROUP BY StudentRollNo HAVING COUNT(StudentRollNo)>1;

SELECT StudentClass, AVG(StudentAge) AS AVG_AGE FROM STUDENT GROUP BY StudentClass ORDER BY StudentClass DESC;

SELECT COUNT(StudentRollNo) AS Total_Count FROM STUDENT GROUP BY StudentRollNo HAVING COUNT(StudentRollNo)>1;

SELECT StudentName FROM STUDENT GROUP BY StudentName HAVING COUNT(StudentName)>1;

INSERT INTO STUDENT VALUES('VEENA','IETLINF01','X',17,'VIJAY');

INSERT INTO STUDENT VALUES('VEENA','IETLINF08','X',17,'VIJAY');

INSERT INTO STUDENT VALUES('VEENA','IETLINF09','VII',15,'KUMAR');

SELECT * FROM STUDENT;

SELECT StudentClass, COUNT(StudentRollNo) AS Total_Count FROM STUDENT GROUP BY StudentClass;

SELECT StudentClass, AVG(StudentAge) AS AVG_AGE FROM STUDENT GROUP BY StudentClass ORDER BY StudentClass DESC;

SELECT StudentName FROM STUDENT GROUP BY StudentName HAVING COUNT(StudentName)>1;

SELECT StudentName,COUNT(StudentName) AS NO_OF_OCCURENCE FROM STUDENT GROUP BY StudentName HAVING COUNT(StudentName)>1;

